[tool.briefcase]
project_name = "ClipSpeech"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/ClipSpeech"
license = "MIT license"
author = 'Oliver.Yeung'
author_email = "oliver.yeung.me@gmail.com"

[tool.briefcase.app.ClipSpeech]
formal_name = "ClipSpeech"
description = "Super speech"
icon = "src/ClipSpeech/resources/ClipSpeech"
sources = ['src/ClipSpeech']
requires = [
    'pyside2==5.13.0',]


[tool.briefcase.app.ClipSpeech.macOS]
requires = []

[tool.briefcase.app.ClipSpeech.linux]
requires = []
system_requires = []

[tool.briefcase.app.ClipSpeech.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.ClipSpeech.iOS]
requires = []

[tool.briefcase.app.ClipSpeech.android]
requires = []
